resources:
- name: istio
  type: git
  source:
    branch: master
    uri: https://github.com/istio/istio

- name: istio-concourse
  type: git
  source:
    branch: master
    uri: https://github.com/rosenhouse/istio-concourse

jobs:
- name: istio-unit
  plan:
  - get: istio-concourse
  - get: istio
    trigger: true
  - task: unit-test
    file: istio-concourse/tasks/istio-unit.yml
