groups:
- name: cf-integration
  jobs:
  - copilot-test
  - istio-release-test
- name: istio
  jobs:
  - istio-unit

resources:
- name: copilot
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/copilot

- name: istio-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/istio-release

- name: istio
  type: git
  source:
    branch: master
    uri: https://github.com/istio/istio

- name: istio-concourse
  type: git
  source:
    branch: master
    uri: https://github.com/rosenhouse/istio-concourse

jobs:
- name: copilot-test
  plan:
  - get: copilot
    trigger: true
  - task: test
    file: copilot/ci/test.yml

- name: istio-release-test
  plan:
  - get: istio-release
    trigger: true
  - task: test
    file: istio-release/ci/istio-tests.yml

- name: istio-unit
  plan:
  - get: istio-concourse
    trigger: true
  - get: istio
    trigger: true
  - task: dep-ensure
    file: istio-concourse/tasks/dep-ensure.yml
    input_mapping: {pre-ensure: istio}
    output_mapping: {post-ensure: istio-with-deps}
    params:
      GOPACKAGE: istio.io/istio
  - task: unit-test
    file: istio-concourse/tasks/istio-unit.yml
