# Runs dep ensure
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: istio/ci
    tag: go1.9-k8s1.7.4

inputs:
- name: pre-ensure

outputs:
- name: post-ensure
  path: go/src/istio.io/istio

run:
  path: /bin/bash
  user: root
  args:
  - -c
  - |
    set -euxo pipefail
    git clone ./pre-ensure go/src/istio.io/istio
    export GOPATH=$PWD/go
    cd go/src/istio.io/istio
    dep ensure -v
