# Runs dep ensure
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: istio/ci
    tag: go1.9-k8s1.7.4

inputs:
- name: pre-ensure

outputs:
- name: post-ensure

params:
  GOPACKAGE=istio.io/istio

run:
  path: /bin/bash
  user: root
  args:
  - -c
  - |
    set -euxo pipefail
    export GOPATH=$PWD/go
    mkdir -p ./go/src/$GOPACKAGE
    git clone ./pre-ensure ./go/src/$GOPACKAGE
    pushd ./go/src/$GOPACKAGE
      dep ensure -v
    popd
    cp -a ./go/src/$GOPACKAGE/ ./post-ensure
