# Concourse Task to run unit tests on https://github.com/istio/istio
# based on the .circleci/config.yml file from the same repo
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: istio/ci
    tag: go1.9-k8s1.7.4

inputs:
- name: istio
  path: go/src/istio.io/istio

run:
  path: /bin/bash
  user: root
  args:
  - -c
  - |
    set -euxo pipefail
    mkdir -p go/bin
    export GOPATH=$PWD/go

    ln -s "$(which etcd)" "$GOPATH/bin/etcd"

    # TODO: perhaps envoy can be a separate resource
    mkdir envoy
    pushd envoy
      ISTIO_PROXY_BUCKET=$(sed 's/ = /=/' <<< $( awk '/ISTIO_PROXY_BUCKET =/' $GOPATH/src/istio.io/istio/WORKSPACE))
      PROXYVERSION=$(sed 's/[^"]*"\([^"]*\)".*/\1/' <<<  $ISTIO_PROXY_BUCKET)
      PROXY=debug-$PROXYVERSION
      wget -qO- https://storage.googleapis.com/istio-build/proxy/envoy-$PROXY.tar.gz | tar xvz
      export ENVOY_BIN=$PWD/usr/local/bin/envoy
    popd

    cd $GOPATH/src/istio.io/istio
    ln -sf $ENVOY_BIN $PWD/pilot/proxy/envoy/envoy

    # TODO: use Concourse caching here
    time dep ensure

    /tmp/apiserver/start-test-server.sh > /dev/null 2>&1 &
    sleep 5 # for server to start

    ln -s $PWD/.circleci/config $PWD/pilot/platform/kube/config
    ln -s $PWD/.circleci/config $PWD/pilot/platform/kube/inject/config
    ln -s $PWD/.circleci/config $PWD/pilot/platform/kube/admit/config
    ln -s $PWD/.circleci/config $PWD/broker/pkg/platform/kube/config

    go test ./pilot/...
    go test ./security/...
    go test ./broker/...
